server:
  port: 2023
  
spring:
  application:
    name: MANAGER-SERVICE
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true    
    service-url:
      defaultZone: http://localhost:8761/eureka/
instance:
  hostname: localhost      